# This is a boilerplate parameters config generated for pipeline 'training'
# using Kedro 0.17.6.
#
# Documentation for this file format can be found in "Parameters"
# Link: https://kedro.readthedocs.io/en/0.17.6/04_kedro_project_setup/02_configuration.html#parameters

stride: 180
fr_horizon: 16
initial: 0.3
score: rmsle

models:
    prophet:
        model_class: time_series_kedro.extras.models.Prophet
        default_args: null
        params:
            all:
                params_search:
                    search: random
                    n_iter: 10
                    params:
                        period: [2, 8, 15, 30]
                        seasonality: [additive, multiplicative]
                        changepoint_prior_scale: stats.loguniform(0.8, 0.95)
                        seasonality_prior_scale: stats.loguniform(0.01, 0.5)
    ridge:
        model_class: time_series_kedro.extras.models.RidgeForecaster
        default_args: null
        params:
            all:
                params_search:
                    search: random
                    n_iter: 20
                    params:
                        lags: [2, 8, 15, 30]
                        alpha: stats.loguniform(0.05, 10.0)
                        n_jobs: [1]
    lasso:
        model_class: time_series_kedro.extras.models.LassoForecaster
        default_args: null
        params:
            all:
                params_search:
                    search: random
                    n_iter: 20
                    params:
                        lags: [2, 8, 15, 30]
                        alpha: stats.loguniform(0.05, 10.0)
                        n_jobs: [1]
    exponential_smoothing:
        model_class: time_series_kedro.extras.models.ExponentialSmoothing
        default_args: null
        params:
            0:
              params_search:
                  search: grid
                  n_iter: 2
                  params:
                      damped_trend: [False]
                      trend: [null]
                      seasonal: [null]
                      seasonal_periods: [2]
            1:
              params_search:
                  search: grid
                  n_iter: 2
                  params:
                      damped_trend: [False, True]
                      trend: [add, mul, null]
                      seasonal: [add, mul, null]
                      seasonal_periods: [2, 8, 15, 29]
            
            all:
              params_search:
                  search: grid
                  n_iter: 2
                  params:
                      damped_trend: [False]
                      trend: [add, null]
                      seasonal: [add, null]
                      seasonal_periods: [15]
